name: wireapps-web-dev

on:
  push:
    branches:
      - main # set main branch
    paths:
      - '/web/**'
  # pull_request:
  #   branches:
  #     - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: cybernaticsuat001.azurecr.io
          username: ${{ secrets.UAT_REGISTRY_USERNAME }}
          password: ${{ secrets.UAT_REGISTRY_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Applications/Backend  ### Change the path
          push: ${{ github.event_name != 'pull_request' }}
          tags: wireappsdev001.azurecr.io/backend:latest,cybernaticsuat001.azurecr.io/backend:${{ github.sha }}
          # cache-from: type=gha, ref=user/app:latest
          # cache-to: type=gha,mode=min

      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: cybernaticsuat001.azurecr.io/backend:latest
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB_TOKEN }}

  deploy: 
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-cybernatics-backend-uat-001' ### Change web app name
          slot-name: 'production'
          publish-profile: ${{ secrets.UAT_Backend_AzureAppService_PublishProfile }}
          images: 'cybernaticsuat001.azurecr.io/backend:latest'